curso/urls.py
from django.urls import path
from . import views

app_name = "cursos"

urlpatterns = [
    path('home',views.Home_curso.as_view(), name='home_curso'),
    path('registro/', views.Create_curso.as_view(), name='create_curso'),   
    path('lista/', views.List_curso.as_view(), name='list_curso'),   
    path('update/<int:pk>/', views.Update_curso.as_view(), name='update_curso'),   
    path('delete/<int:pk>/', views.Delete_curso.as_view(), name='delete_curso'),   
]

professor/urls.py
from django.urls import path
from . import views

app_name = 'professores'

urlpatterns = [
    path('home',views.Home_professor.as_view(),name='home_professor'),
    path('registro/', views.Create_professor.as_view(), name='create_professor'),
    path('lista/', views.List_professor.as_view(), name='list_professor'),   
    path('update/<int:pk>/', views.Update_professor.as_view(), name='update_professor'),
    path('delete/<int:pk>/', views.Delete_professor.as_view(), name='delete_professor'),      
]

setup/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls.conf import include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('cursos/',include('curso.urls',namespace="cursos")),
    path('professores/',include('professor.urls',namespace='professores')),
    path('disciplinas/',include('disciplina.urls',namespace='disciplinas')),
    path('disponibilidades/',include('disponibilidade.urls',namespace='disponibilidades')),
    path('turmas/',include('turma.urls',namespace="turmas")),
]

professor/models.py
from django.db import models
from disponibilidade.models import Disponibilidade
# Create your models here.

class Professor(models.Model):
    nome = models.CharField(max_length=255)
    suap = models.CharField(max_length=100, unique=True)
    coordenador = models.BooleanField(default=False)
    disponibilidade_professor = models.ManyToManyField(Disponibilidade)
    email = models.EmailField()
    telefone = models.CharField(max_length=16)

    def __str__(self):
        return self.nome

professor/views.py
from django.shortcuts import render
from django.views.generic import View,CreateView, UpdateView,ListView,DeleteView
from professor.models import Professor
from django.urls import reverse_lazy
# Create your views here.

class Home_professor(View):
    
    def get(self, request):
        return render(request, 'professor/home_professor.html')

class Create_professor(CreateView):
    model = Professor
    template_name = 'professor/create_professor.html'
    fields = ['nome','suap','coordenador','disponibilidade_professor','email','telefone']
    success_url = reverse_lazy('professores:list_professor')

    def form_valid(self, form):
        return super().form_valid(form)

class List_professor(ListView):
    template_name: str = 'professor/list_professor.html'

    def get_queryset(self):
        queryset = Professor.objects.all()
        return queryset

class Update_professor(UpdateView):    
    model =Professor
    template_name = 'professor/create_professor.html'
    fields = ['nome','suap','coordenador','disponibilidade_professor','email','telefone']
    success_url = reverse_lazy('professores:list_professor')

    def form_valid(self, form):
        return super().form_valid(form)

class Delete_professor(DeleteView):
    model =Professor
    template_name = 'professor/delete_professor.html'
    success_url = reverse_lazy('professores:list_professor')

    def get_success_url(self):
        return reverse_lazy('professores:list_professor')

templates/professor/create_professor.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
    <h2>Cadastro de professores</h2>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-success ">Salvar</button>
    </form>
{% endblock %}

templates/professor/delete_professor.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
    <h2>Exclusão de professores</h2>
    <p>Deseja realmente excluir o professor: <strong>{{ object }}</strong>?</p>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-danger ">Delete</button>
    </form>
{% endblock %}

templates/professor/home_professor.html
{% extends '../home.html' %}

    <body>
        {% block container %}
        <h2>Página dos professores</h2>
        <p>Aqui você administrará os professores dessa escola</p>
        <h3>Opções</h3>
        <a href="{% url 'professores:create_professor' %}">
            <button type="button" class="btn btn-primary btn-lg btn-block">Cadastrar professor</button>
        </a>
        <br>
        <a href="{% url 'professores:list_professor' %}">
            <button type="button" class="btn btn-primary btn-lg btn-block">Listar professores</button>
        </a>
        {% endblock %}
    </body>
</html>

templates/professor/list_professor.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
<h1>Lista de disponibilidades de professores</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                SUAP
            </th>
            <th>
                Coordenador
            </th>
            <th>
                Disponibilidades
            </th>
            <th>
                Opções
            </th>
        </tr>
    </thead>
    <tbody>
        {% for professor in object_list %}
        <tr>
            <td>
                {{ professor.nome }}
            </td>
            <td>
                {{ professor.suap}}
            </td>
            <td>
                {{ professor.coordenador}}
            </td>
            <td>
                {% for disponibilidade in professor.disponibilidade_professor.all %}
                    {{disponibilidade}}<br> 
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'professores:update_professor' professor.id %}" class="text-primary">Alterar</a>
                <a href="{% url 'professores:delete_professor' professor.id %}" class="text-danger">Apagar</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}