curso/urls.py
from django.urls import path
from . import views

app_name = "cursos"

urlpatterns = [
    path('home',views.Home_curso.as_view(), name='home_curso'),
    path('registro/', views.Create_curso.as_view(), name='create_curso'),   
    path('lista/', views.List_curso.as_view(), name='list_curso'),   
    path('update/<int:pk>/', views.Update_curso.as_view(), name='update_curso'),   
    path('delete/<int:pk>/', views.Delete_curso.as_view(), name='delete_curso'),   
]

disciplina/urls.py
from django.urls import path
from . import views

app_name = 'disciplinas'

urlpatterns = [
    path('home/',views.Home_disciplina.as_view(), name='home_disciplina'),
    path('registro/', views.Create_disciplina.as_view(), name='create_disciplina'),
    path('lista/', views.List_disciplina.as_view(), name='list_disciplina'),   
    path('update/<int:pk>/', views.Update_disciplina.as_view(), name='update_disciplina'),
    path('delete/<int:pk>/', views.Delete_disciplina.as_view(), name='delete_disciplina'),      
]

setup/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls.conf import include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('cursos/',include('curso.urls',namespace="cursos")),
    path('professores/',include('professor.urls',namespace='professores')),
    path('disciplinas/',include('disciplina.urls',namespace='disciplinas')),
    path('disponibilidades/',include('disponibilidade.urls',namespace='disponibilidades')),
    path('turmas/',include('turma.urls',namespace="turmas")),
]

disciplina/models.py
from django.db import models
from professor.models import Professor
from curso.models import Curso
# Create your models here.

class Disciplina(models.Model):
    nome = models.CharField(max_length=255)
    carga_horaria = models.IntegerField()
    aulas_por_semana = models.IntegerField()#Para definir a quantidade de aulas por semana
    curso_disciplina = models.ForeignKey(Curso,on_delete=models.CASCADE)
    profesor_disciplina = models.ForeignKey(Professor,on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

disciplina/views.py
from django.shortcuts import render
from django.views.generic import View,CreateView, UpdateView,ListView, DeleteView
from disciplina.models import Disciplina
from django.urls import reverse_lazy
# Create your views here.

class Home_disciplina(View):
    
    def get(self, request):
        return render(request, 'disciplina/home_disciplina.html')

class Create_disciplina(CreateView):
    model = Disciplina
    template_name = 'disciplina/create_disciplina.html'
    fields = ['nome','carga_horaria','aulas_por_semana','curso_disciplina','profesor_disciplina']
    success_url = reverse_lazy('disciplinas:list_disciplina')

    def form_valid(self, form):
        return super().form_valid(form)

class Update_disciplina(UpdateView):
    model = Disciplina
    template_name: str = 'disciplina/create_disciplina.html'
    fields = ['nome','carga_horaria','aulas_por_semana','curso_disciplina','profesor_disciplina']
    success_url = reverse_lazy('disciplinas:list_disciplina')

    def form_valid(self, form):
        return super().form_valid(form)

class List_disciplina(ListView):
    template_name: str = 'disciplina/list_disciplina.html'

    def get_queryset(self):
        queryset = Disciplina.objects.all()
        return queryset

class Delete_disciplina(DeleteView):
    model =Disciplina
    template_name = 'disciplina/delete_disciplina.html'
    success_url = reverse_lazy('disciplinas:list_disciplina')

    def get_success_url(self):
        return reverse_lazy('disciplinas:list_disciplina')

templates/disciplina/create_disciplina.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
    <h2>Cadastro de disciplinas</h2>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-success ">Salvar</button>
    </form>
{% endblock %}

templates/disciplina/delete_disciplina.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
<h2>Exclusão de disciplinas</h2>
<p>Deseja realmente excluir a disponibilidade: <strong>{{ object }}</strong>?</p>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-danger ">Delete</button>
    </form>
{% endblock %}

templates/disciplina/home_disciplina.html
{% extends '../home.html' %}

    <body>
        {% block container %}
        <h2>Página das disciplinas</h2>
        <p>Aqui você administrará as disciplinas dessa escola</p>
        <h3>Opções</h3>
        <a href="{% url 'disciplinas:create_disciplina' %}">
            <button type="button" class="btn btn-primary btn-lg btn-block">Cadastrar disciplina</button>
        </a>
        <br>
        <a href="{% url 'disciplinas:list_disciplina' %}">
            <button type="button" class="btn btn-primary btn-lg btn-block">Listar disciplinas</button>
        </a>
        {% endblock %}
    </body>
</html>

templates/disciplina/list_disciplina.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
<h1>Lista de disciplinas</h1>

<table  class="table table-bordered">
    <thead>
        <tr>
            <th>
                Disciplina
            </th>
            <th>
                Professor da disciplina
            </th>
            <th>
                Curso da disciplina
            </th>
            <th>
                Carga horária
            </th>
            <th>
                Opções
            </th>
        </tr>
    </thead>
    <tbody>
        {% for disciplina in object_list %}
        <tr>
            <td>
                {{ disciplina.nome }}
            </td>
            <td>
                {{ disciplina.profesor_disciplina.nome }}
            </td>
            <td>
                {{ disciplina.curso_disciplina.nome }}
            </td>
            <td>
                {{ disciplina.carga_horaria}} 
            </td>
            <td>
                <a href="{% url 'disciplinas:update_disciplina' disciplina.id %}" class="text-primary">
                    Alterar
                </a>
                <a href="{% url 'disciplinas:delete_disciplina' disciplina.id %}" class="text-danger">
                    Apagar
                </a>
            </td>
        </tr>
        {% endfor %}      
    </tbody>
</table>
{% endblock %}