curso/urls.py
from django.urls import path
from . import views

app_name = "cursos"

urlpatterns = [
    path('home',views.Home_curso.as_view(), name='home_curso'),
    path('registro/', views.Create_curso.as_view(), name='create_curso'),   
    path('lista/', views.List_curso.as_view(), name='list_curso'),   
    path('update/<int:pk>/', views.Update_curso.as_view(), name='update_curso'),   
    path('delete/<int:pk>/', views.Delete_curso.as_view(), name='delete_curso'),   
]

disciplina/urls.py
from django.urls import path
from . import views

app_name = 'disciplinas'

urlpatterns = [
    path('home/',views.Home_disciplina.as_view(), name='home_disciplina'),
    path('registro/', views.Create_disciplina.as_view(), name='create_disciplina'),
    path('lista/', views.List_disciplina.as_view(), name='list_disciplina'),   
    path('update/<int:pk>/', views.Update_disciplina.as_view(), name='update_disciplina'),
    path('delete/<int:pk>/', views.Delete_disciplina.as_view(), name='delete_disciplina'),      
]

disponibilidade/urls.py
from django.urls import path
from . import views

app_name='disponibilidades'

urlpatterns = [
    path('home/',views.Home_disponibilidade.as_view(),name='home_disponibilidade'),
    path('registro/', views.Create_dispnibilidade.as_view(), name='create_disponibilidade'),   
    path('lista/', views.List_disponibilidade.as_view(), name='list_disponibilidade'),   
    path('update/<int:pk>/', views.Update_disponibilidade.as_view(), name='update_disponibilidade'),
    path('delete/<int:pk>/', views.Delete_disponibilidade.as_view(), name='delete_disponibilidade'),         
]

professor/urls.py
from django.urls import path
from . import views

app_name = 'professores'

urlpatterns = [
    path('home',views.Home_professor.as_view(),name='home_professor'),
    path('registro/', views.Create_professor.as_view(), name='create_professor'),
    path('lista/', views.List_professor.as_view(), name='list_professor'),   
    path('update/<int:pk>/', views.Update_professor.as_view(), name='update_professor'),
    path('delete/<int:pk>/', views.Delete_professor.as_view(), name='delete_professor'),      
]

setup/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls.conf import include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('cursos/',include('curso.urls',namespace="cursos")),
    path('professores/',include('professor.urls',namespace='professores')),
    path('disciplinas/',include('disciplina.urls',namespace='disciplinas')),
    path('disponibilidades/',include('disponibilidade.urls',namespace='disponibilidades')),
    path('turmas/',include('turma.urls',namespace="turmas")),
]

turma/urls.py
from django.urls import path
from . import views

app_name = "turmas"

urlpatterns = [
    path('home/',views.Home_turma.as_view(),name='home_turma'),
    path('registro/', views.Create_turma.as_view(), name='create_turma'),
    path('lista/', views.List_turma.as_view(), name='list_turma'),   
    path('update/<int:pk>/', views.Update_turma.as_view(), name='update_turma'),
    path('delete/<int:pk>/', views.Delete_turma.as_view(), name='delete_turma'),            
]

templates/home.html
{% load static %}
<html>
    <head>
        <title>Django gerador de horarios</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <title>Django + Bootstrap</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Projeto Horarios</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'professores:home_professor' %}">
                                Professores <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'disponibilidades:home_disponibilidade' %}">
                                Disponibilidade <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'disciplinas:home_disciplina' %}">
                                Disciplinas
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cursos:home_curso' %}">
                                Cursos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'turmas:home_turma' %}">
                                Turmas
                            </a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Procucar</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-8">
                <hr class="mt-0 mb-4">
                {% block container %}

                    <h1>Seja bem vindo!</h1>
                    <p>Este sistema irá gerar seu horário escolar</p>
                    
                    <a href="{% url 'professores:home_professor' %}">
                        <button type="button" class="btn btn-primary btn-lg btn-block">Professores</button>
                    </a><br>
                    <a href="{% url 'disponibilidades:home_disponibilidade' %}">
                        <button type="button" class="btn btn-primary btn-lg btn-block">Disponibilidades</button>
                    </a><br>
                    <a href="{% url 'disciplinas:home_disciplina' %}">
                        <button type="button" class="btn btn-primary btn-lg btn-block">Disciplinas</button>
                    </a><br>
                    <a href="{% url 'cursos:home_curso' %}">
                        <button type="button" class="btn btn-primary btn-lg btn-block">Cursos</button>
                    </a><br>
                    <a href="{% url 'turmas:home_turma' %}">
                        <button type="button" class="btn btn-primary btn-lg btn-block">Turmas</button>
                    </a>


                {% endblock %}
            </div>
        </div>
      </div>
    </body>
</html>