curso/urls.py
from django.urls import path
from . import views

app_name = "cursos"

urlpatterns = [
    path('home',views.Home_curso.as_view(), name='home_curso'),
    path('registro/', views.Create_curso.as_view(), name='create_curso'),   
    path('lista/', views.List_curso.as_view(), name='list_curso'),   
    path('update/<int:pk>/', views.Update_curso.as_view(), name='update_curso'),   
    path('delete/<int:pk>/', views.Delete_curso.as_view(), name='delete_curso'),   
]

disponibilidade/urls.py
from django.urls import path
from . import views

app_name='disponibilidades'

urlpatterns = [
    path('home/',views.Home_disponibilidade.as_view(),name='home_disponibilidade'),
    path('registro/', views.Create_dispnibilidade.as_view(), name='create_disponibilidade'),   
    path('lista/', views.List_disponibilidade.as_view(), name='list_disponibilidade'),   
    path('update/<int:pk>/', views.Update_disponibilidade.as_view(), name='update_disponibilidade'),
    path('delete/<int:pk>/', views.Delete_disponibilidade.as_view(), name='delete_disponibilidade'),         
]

setup/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls.conf import include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('cursos/',include('curso.urls',namespace="cursos")),
    path('professores/',include('professor.urls',namespace='professores')),
    path('disciplinas/',include('disciplina.urls',namespace='disciplinas')),
    path('disponibilidades/',include('disponibilidade.urls',namespace='disponibilidades')),
    path('turmas/',include('turma.urls',namespace="turmas")),
]

disponibilidade/models.py
from django.db import models

# Create your models here.

class Disponibilidade(models.Model):
    DIAS_SEMANA = (
        ('SEGUNDA','Segunda-feira'),
        ('TERÇA','Terça-feira'),
        ('QUARTA','Quarta-feira'),
        ('QUINTA','Quinta-feira'),
        ('SEXTA','Sexta-feira'),
    )
    dia_semana = models.CharField(max_length=8,choices=DIAS_SEMANA)

    def __str__(self):
        return self.dia_semana

disponibilidade/views.py
from django.shortcuts import render
from django.views.generic import View,CreateView,UpdateView,ListView,DeleteView
from disponibilidade.models import Disponibilidade
from django.urls import reverse_lazy
# Create your views here.

class Home_disponibilidade(View):
    
    def get(self, request):
        return render(request, 'disponibilidade/home_disponibilidade.html')

class Create_dispnibilidade(CreateView):
    model = Disponibilidade
    template_name = 'disponibilidade/create_disponibilidade.html'
    fields = ['dia_semana',]
    success_url = reverse_lazy('disponibilidades:list_disponibilidade')

    def form_valid(self, form):
        return super().form_valid(form)

class List_disponibilidade(ListView):
    template_name: str = 'disponibilidade/list_disponibilidade.html'

    def get_queryset(self):
        queryset = Disponibilidade.objects.all()
        return queryset

class Update_disponibilidade(UpdateView):    
    model =Disponibilidade
    template_name = 'disponibilidade/create_disponibilidade.html'
    fields = ['dia_semana',]
    success_url = reverse_lazy('disponibilidades:list_disponibilidade')

    def form_valid(self, form):
        return super().form_valid(form)

class Delete_disponibilidade(DeleteView):
    model =Disponibilidade
    template_name = 'disponibilidade/delete_disponibilidade.html'
    success_url = reverse_lazy('disponibilidades:list_disponibilidade')

    def get_success_url(self):
        return reverse_lazy('disponibilidades:list_disponibilidade')

templates/disponibilidade/create_disponibilidade.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
    <h2>Cadastro de disponibilidade</h2>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-success ">Salvar</button>
    </form>
{% endblock %}

templates/disponibilidade/delete_disponibilidade.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
<h2>Exclusão de disponibilidades</h2>
<p>Deseja realmente excluir a disponibilidade: <strong>{{ object }}</strong>?</p>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-danger ">Delete</button>
    </form>
{% endblock %}

templates/disponibilidade/home_disponibilidade.html
{% extends '../home.html' %}

{% block container %}
    <h2>Página de disponibilidades</h2>
    <p>Aqui você administrará as disponibilidades dos professores dessa escola</p>
    <h3>Opções</h3>
    <a href="{% url 'disponibilidades:create_disponibilidade' %}">
        <button type="button" class="btn btn-primary btn-lg btn-block">Cadastrar disponibilidade</button>
    </a>
    <br>
    <a href="{% url 'disponibilidades:list_disponibilidade' %}">
        <button type="button" class="btn btn-primary btn-lg btn-block">Listar disponibilidades</button>
    </a>
{% endblock  %}

templates/disponibilidade/list_disponibilidade.html
{% extends '../home.html' %}
{% load crispy_forms_tags %}
{% block container %}
<h1>Lista de disponibilidades de professores</h1>
<br>
    {% for disponibilidade in object_list %}
        <tr>
            <td>
                <p><strong>Disponibilidade:</strong>{{ disponibilidade.dia_semana }}
            
                <a href="{% url 'disponibilidades:update_disponibilidade' disponibilidade.id  %}" class="text-primary">
                    Alterar
                </a>
            
                <a href="{% url 'disponibilidades:delete_disponibilidade' disponibilidade.id %}" class="text-danger">
                    Apagar
                </a>
                </p>
            </td>   
        </tr>
    {% endfor %}
{% endblock %}